# Generated by Django 4.1.6 on 2023-02-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(blank=True, max_length=16, null=True)),
                ('field2', models.CharField(blank=True, max_length=16, null=True)),
                ('field3', models.CharField(blank=True, max_length=16, null=True)),
                ('field4', models.CharField(blank=True, max_length=16, null=True)),
                ('field5', models.CharField(blank=True, max_length=16, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
