# Generated by Django 4.1.6 on 2023-02-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamodel',
            name='field1',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='field2',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='field3',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='field4',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='field5',
        ),
        migrations.AddField(
            model_name='datamodel',
            name='SKU',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='client_joined_voice',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='client_reacted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='client_watched_stream',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='client_watched_stream_record',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='endpoint',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='guest_client_joined',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='page_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='request_datetime',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='seconds_till_receive',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='session',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='session_finished',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='session_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='session_streams_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='shop_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='stream_datetime_second',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='stream_durability',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='stream_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='stream_mark',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='streamer',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='target',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='worker_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
