# Generated by Django 4.1.6 on 2023-02-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_datamodel_field1_remove_datamodel_field2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='client_joined_voice',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='client_reacted',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='client_watched_stream',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='client_watched_stream_record',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
