# Generated by Django 4.1.6 on 2023-02-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_datamodel_client_joined_voice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamodel',
            name='SKU',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='client_joined_voice',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='client_reacted',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='client_watched_stream',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='client_watched_stream_record',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='guest_client_joined',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='page_url',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='request_datetime',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='seconds_till_receive',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='session',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='session_finished',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='session_streams_count',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='shop_id',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='stream_datetime_second',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='stream_durability',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='stream_link',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='stream_mark',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='streamer',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='target',
        ),
        migrations.RemoveField(
            model_name='datamodel',
            name='worker_id',
        ),
        migrations.AddField(
            model_name='datamodel',
            name='createdAt',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='duration',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='isStreamMade',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='logUrl',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='rating',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='streamsNumber',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='websiteUrl',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
