# Generated by Django 4.1.6 on 2023-02-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_datamodel_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
    ]
