# Generated by Django 4.1.6 on 2023-03-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_datamodel_createdat_alter_datamodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='streamer',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
